version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:


volumes:
  grafana-storage:
